# -*- coding: utf-8 -*-
"""job_rec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q8d-YIHrchfRTKut5rsspvODlbQlCw2b

**K-Nearest Neighbors**

We are going to build a KNN model that would recommend jobs based on your experience and skills

Key Concept: The user should enter the skills and experience they have and the knn model would return k nearest plots matching the skills and experience and after it return the skills and experience, then the company and lpa will be returned to the user with the help of hashing

**Importing the nexcessary packages**

pandas - to load csv files, datacleaning and preprocessing before vectorization
"""

import pandas as pd

"""numpy - to handle numerical values, helps to build knn which works with only numerical data"""

import numpy as np

"""CountVectorizer - to convert the text(skills) to vectors"""

from sklearn.feature_extraction.text import CountVectorizer

"""for scaling-> using minmax scaler"""

from sklearn.preprocessing import MinMaxScaler

"""importing the knn model"""

from sklearn.neighbors import NearestNeighbors

"""Loading the dataset"""

df = pd.read_csv("dataset/job_dataset.csv")

"""creating a hashed columns for company names for final output"""

df["company_hash"]=df["company_name"].apply(lambda x:hash(x)%100000)

"""mapping the companies and their lpa"""

output_hash_map={
    idx:{
        "company_hash":row["company_hash"],
        "lpa":row["lpa"]
    }
    for idx,row in df.iterrows()
}

"""reverse mapping to find the company name with the help of company_hash"
"""

company_reverse_map={
    row["company_hash"]:row["company_name"]
    for _,row in df.iterrows()
}

""" Data Cleaning and preprocessing to make there is no invalid data in skill section and to convert the skills as a string(" ") to python-list format"""

def clean_skills(text):
  parts=text.split(",")
  parts=[p.strip().lower() for p in parts]
  parts=[p for p in parts if p]
  return parts
df["skills_clean"]=df["skills"].apply(clean_skills)
df[["skills_clean","skills"]].head()

"""Since the KNN model cannot interpret texts, we will start vectorizing the skills"""

# Convert list of skills into space-separated strings
df["skills_joined"] = df["skills_clean"].apply(lambda skills: " ".join(skills))

# Initialize the vectorizer
skill_vectorizer = CountVectorizer()

# Fit and transform to get the skill vectors
skill_vectors = skill_vectorizer.fit_transform(df["skills_joined"])

# Convert to array for KNN usage
skill_vectors = skill_vectors.toarray()

# Show the vocabulary (all skills)
print("Skill Vocabulary:", skill_vectorizer.get_feature_names_out()[:20])
print("Vector shape:", skill_vectors.shape)

"""Normalization - since the skills are in 0/1 , big integer experience would affect the knn model to find the neighbors based on their skills so we have are normalizing the experience years to be in the range of [0,1]"""

exp_values=df[["experience_needed"]]
exp_scaler=MinMaxScaler()
exp_normalised=exp_scaler.fit_transform(exp_values)
df["experience_normalised"]=exp_normalised
df[["experience_needed","experience_normalised"]].head()

"""Constructing KNN vectors to build knn model"""

exp_vectors=df["experience_normalised"].values.reshape(-1,1)
knn_vectors=np.hstack((skill_vectors,exp_vectors))
print("Skill Vectors Shape: ",skill_vectors.shape)
print("Experience vector shape: ",exp_vectors.shape)
print("KNN Vectors Shape :",knn_vectors.shape)

"""Let's train the KNN model to find 5 nearest neighbors and use cosine similarity to calculate the distance"""

knn_model=NearestNeighbors(
    n_neighbors=5,
    metric="cosine"

)
knn_model.fit(knn_vectors)
import joblib

joblib.dump(knn_model, "knn_model.pkl")
user_skills=["python","sql","c++"]
user_experience=3
user_skills_joined=" ".join(user_skills)
user_skill_vector=skill_vectorizer.transform([user_skills_joined])
user_exp_norm=exp_scaler.transform([[user_experience]])
user_vector=np.hstack((user_skill_vector.toarray(),user_exp_norm))
distances,indices=knn_model.kneighbors(user_vector)
print("Recommended Jobs")
for idx in indices[0]:
    company_hash = output_hash_map[idx]["company_hash"]
    lpa = output_hash_map[idx]["lpa"]
    company_name = company_reverse_map[company_hash]

    print(f"Company: {company_name}")
    print(f"LPA: {lpa}")
    print(f"Skills: {df.loc[idx, 'skills_clean']}")
    print(f"Experience Needed: {df.loc[idx, 'experience_needed']} years")
    print("-" * 40)
